//
// Content.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Content: Codable, JSONEncodable, Hashable {

    public var schemaRef: String?
    public var data: AnyCodable?

    public init(schemaRef: String? = nil, data: AnyCodable? = nil) {
        self.schemaRef = schemaRef
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaRef
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaRef, forKey: .schemaRef)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

