//
// DataStoreTransactions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DataStoreTransactions: Codable, JSONEncodable, Hashable {

    public var add: [ItemOfAdd]?
    public var remove: [ItemOfRemove]?

    public init(add: [ItemOfAdd]? = nil, remove: [ItemOfRemove]? = nil) {
        self.add = add
        self.remove = remove
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case add
        case remove
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(add, forKey: .add)
        try container.encodeIfPresent(remove, forKey: .remove)
    }
}

