//
// ErrorResponseValidationErrorsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ErrorResponseValidationErrorsInner: Codable, JSONEncodable, Hashable {

    public var message: String?
    public var kind: String?
    public var path: String?

    public init(message: String? = nil, kind: String? = nil, path: String? = nil) {
        self.message = message
        self.kind = kind
        self.path = path
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case kind
        case path
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(path, forKey: .path)
    }
}

