//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelErrorResponse: Codable, JSONEncodable, Hashable {

    public var message: String?
    /** Key value pair of errors */
    public var validationErrors: [ErrorResponseValidationErrorsInner]?

    public init(message: String? = nil, validationErrors: [ErrorResponseValidationErrorsInner]? = nil) {
        self.message = message
        self.validationErrors = validationErrors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case validationErrors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(validationErrors, forKey: .validationErrors)
    }
}

