//
// Scene1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Scene1: Codable, JSONEncodable, Hashable {

    public var placement: String?

    public init(placement: String? = nil) {
        self.placement = placement
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case placement
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(placement, forKey: .placement)
    }
}

