//
// ServerEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerEvent: Codable, JSONEncodable, Hashable {

    public var session: SessionBody?
    public var events: [Event]?

    public init(session: SessionBody? = nil, events: [Event]? = nil) {
        self.session = session
        self.events = events
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case session
        case events
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(session, forKey: .session)
        try container.encodeIfPresent(events, forKey: .events)
    }
}

