//
// ServerBrick.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerBrick: Codable, JSONEncodable, Hashable {

    public var session: SessionData?
    public var data: [ServerBrickDataInner]?

    public init(session: SessionData? = nil, data: [ServerBrickDataInner]? = nil) {
        self.session = session
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case session
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(session, forKey: .session)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

