//
// ServerBrickDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerBrickDataInner: Codable, JSONEncodable, Hashable {

    public enum StatusCode: Double, Codable, JSONEncodable, CaseIterable {
        case _200 = 200
        case _500 = 500
        case _501 = 501
    }
    public var eventId: String?
    public var statusCode: StatusCode?
    public var bricks: [Brick]?

    public init(eventId: String? = nil, statusCode: StatusCode? = nil, bricks: [Brick]? = nil) {
        self.eventId = eventId
        self.statusCode = statusCode
        self.bricks = bricks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventId
        case statusCode
        case bricks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(eventId, forKey: .eventId)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
        try container.encodeIfPresent(bricks, forKey: .bricks)
    }
}

