//
// SessionBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionBody: Codable, JSONEncodable, Hashable {

    /** Refers to User */
    public var userId: String?
    /** an array of secondary ids to eventually find a user by any of them */
    public var secondaryIds: [String]?

    public init(userId: String? = nil, secondaryIds: [String]? = nil) {
        self.userId = userId
        self.secondaryIds = secondaryIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case secondaryIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(secondaryIds, forKey: .secondaryIds)
    }
}

