//
// SessionData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionData: Codable, JSONEncodable, Hashable {

    /** Refers to User */
    public var userId: String?
    /** Refers to Topic */
    public var topicId: String?

    public init(userId: String? = nil, topicId: String? = nil) {
        self.userId = userId
        self.topicId = topicId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case topicId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(topicId, forKey: .topicId)
    }
}

