//
// Ttl.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Ttl: Codable, JSONEncodable, Hashable {

    public enum Unit: String, Codable, CaseIterable {
        case milliseconds = "milliseconds"
        case seconds = "seconds"
        case minutes = "minutes"
        case hours = "hours"
        case days = "days"
        case months = "months"
        case years = "years"
    }
    public var amount: Double?
    public var unit: Unit? = .milliseconds

    public init(amount: Double? = nil, unit: Unit? = .milliseconds) {
        self.amount = amount
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(unit, forKey: .unit)
    }
}

