//
// EventAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class EventAPI {

    /**

     - parameter channelId: (path) channelId 
     - parameter userId: (path) a user identification 
     - parameter topicId: (path) a topic identification 
     - parameter event: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func processEvent(channelId: String, userId: String, topicId: String, event: [Event], apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [Brick]?, _ error: Error?) -> Void)) -> RequestTask {
        return processEventWithRequestBuilder(channelId: channelId, userId: userId, topicId: topicId, event: event).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/channels/{channelId}/users/{userId}/topics/{topicId}/events
     - processes a new Event to be processed by the AI
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: api_token
     - API Key:
       - type: apiKey ApiSecret (HEADER)
       - name: api_secret
     - responseHeaders: [X-Event(String)]
     - parameter channelId: (path) channelId 
     - parameter userId: (path) a user identification 
     - parameter topicId: (path) a topic identification 
     - parameter event: (body)  
     - returns: RequestBuilder<[Brick]> 
     */
    open class func processEventWithRequestBuilder(channelId: String, userId: String, topicId: String, event: [Event]) -> RequestBuilder<[Brick]> {
        var localVariablePath = "/api/v1/channels/{channelId}/users/{userId}/topics/{topicId}/events"
        let channelIdPreEscape = "\(APIHelper.mapValueToPathItem(channelId))"
        let channelIdPostEscape = channelIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{channelId}", with: channelIdPostEscape, options: .literal, range: nil)
        let userIdPreEscape = "\(APIHelper.mapValueToPathItem(userId))"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{userId}", with: userIdPostEscape, options: .literal, range: nil)
        let topicIdPreEscape = "\(APIHelper.mapValueToPathItem(topicId))"
        let topicIdPostEscape = topicIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{topicId}", with: topicIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: event)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Brick]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
