//
// Server2ServerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class Server2ServerAPI {

    /**

     - parameter channelId: (path) channelId 
     - parameter serverEvent: (body)  
     - parameter apiSecret: (header) ApiSecret (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func serverToServerProcessEvent(channelId: String, serverEvent: [ServerEvent], apiSecret: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ServerBrick?, _ error: Error?) -> Void)) -> RequestTask {
        return serverToServerProcessEventWithRequestBuilder(channelId: channelId, serverEvent: serverEvent, apiSecret: apiSecret).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/channels/{channelId}/events
     - processes a new Event to be processed by the AI
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: api_token
     - API Key:
       - type: apiKey ApiSecret (HEADER)
       - name: api_secret
     - parameter channelId: (path) channelId 
     - parameter serverEvent: (body)  
     - parameter apiSecret: (header) ApiSecret (optional)
     - returns: RequestBuilder<ServerBrick> 
     */
    open class func serverToServerProcessEventWithRequestBuilder(channelId: String, serverEvent: [ServerEvent], apiSecret: String? = nil) -> RequestBuilder<ServerBrick> {
        var localVariablePath = "/api/v1/channels/{channelId}/events"
        let channelIdPreEscape = "\(APIHelper.mapValueToPathItem(channelId))"
        let channelIdPostEscape = channelIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{channelId}", with: channelIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: serverEvent)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "ApiSecret": apiSecret?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServerBrick>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
